// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLufRYRD-Gunc_peF-VXi_hnkIK3EXng',
    appId: '1:1070495680802:web:bee2cb6e31184bdf76bd7b',
    messagingSenderId: '1070495680802',
    projectId: 'disability-b72ac',
    authDomain: 'disability-b72ac.firebaseapp.com',
    storageBucket: 'disability-b72ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlchlBq5bSpzdc0Apzc54fZrThxgU1pxg',
    appId: '1:1070495680802:android:da9bfd3ca3f1c46576bd7b',
    messagingSenderId: '1070495680802',
    projectId: 'disability-b72ac',
    storageBucket: 'disability-b72ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIhY4Ka8nKjJL4gMBl7XC5bf9JzuTy0gQ',
    appId: '1:1070495680802:ios:a603f2f8a9ad16fd76bd7b',
    messagingSenderId: '1070495680802',
    projectId: 'disability-b72ac',
    storageBucket: 'disability-b72ac.firebasestorage.app',
    iosBundleId: 'com.example.disability',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIhY4Ka8nKjJL4gMBl7XC5bf9JzuTy0gQ',
    appId: '1:1070495680802:ios:a603f2f8a9ad16fd76bd7b',
    messagingSenderId: '1070495680802',
    projectId: 'disability-b72ac',
    storageBucket: 'disability-b72ac.firebasestorage.app',
    iosBundleId: 'com.example.disability',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLufRYRD-Gunc_peF-VXi_hnkIK3EXng',
    appId: '1:1070495680802:web:a4e27c0ecea58f1f76bd7b',
    messagingSenderId: '1070495680802',
    projectId: 'disability-b72ac',
    authDomain: 'disability-b72ac.firebaseapp.com',
    storageBucket: 'disability-b72ac.firebasestorage.app',
  );

}